services:
  cache:
    image: redis:8.2.3-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASS}
    volumes:
      - cache:/data
    environment:
      - REDIS_PASS=${REDIS_PASS}

volumes:
  cache:
    driver: local
